### ISSUE TITLE
Lossless / quality option

### ISSUE THREAD

**Issue by camlafit** [VirtuBox/img-optimize#2]
Hello

Thanks for your script, it's very nice and simple :)
If I've correctly understood, some quality value are set by defaul. Could be possible to have an option to set quality option ?

Thanks

**Comment by VirtuBox** [comment]
Hello,

currently, for JPG images, quality is set to 82 (JPG optimization & WebP conversion).
For PNG images, there is no quality settings, but only the optimization level currently set to 7 (240 trials), and it's the same for PNG -> WebP conversion.
It should be possible to add an option for PNG & JPG images optimization, but it will be harder for WebP conversion because I'm not sure how to pass the variable into the script.

**Comment by camlafit** [comment]
Hello

Could be interessting to reopen this issue. With #7 PR could be easier to solve this issue.
